[package]
name = "kast-playground"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kast = { git = "https://github.com/kast-lang/kast" }
wasm-bindgen = "0.2.95"
js-sys = "0.3"
