name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  pages:
    name: Pages
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'kast-lang'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/trunk-action@v0.5.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - run: trunk build --release
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist